### ISSUE TITLE
crash or missing mesh

### ISSUE THREAD

**Issue by Franada** [Perfare/AssetStudio#323]
with an older version I was able to export a file, but its as some material issue and duplicate mesh for map. And now with the last version, the program crash when exporting like a character and this time map that as duplicate now miss some mesh. When would we be able to import in blender. I got an error or all the bone are x in the air and do nothing

https://mega.nz/#F!uyoHDK4Y!_NzBMOslUSAT6TPpUzQoSw

**Comment by Perfare** [comment]
mob_model_3 : bug fixed in 761579ab1a6581cf733d275f0b5492716fddb5c0
stage002.ab : combine mesh have a location problem and haven't fixed it yet.

**Comment by Franada** [comment]
Its still crash and for the one that pass the rig is really mes top 

https://gyazo.com/a0911b6d55c65bd4c273c40ded16e390

https://mega.nz/#!OyQ2FQ4S!PJVXZjfCwPnofMVNNGYlT9AvYgbjaxcmifWi6wgfuNA

**Comment by Perfare** [comment]
Are you using the latest version of AssetStudio? I tested this file and work fine.

**Comment by Franada** [comment]
look like its didn't DL the last version.

I download the 761579ab on https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

No crash

But it look like the rig is destroy on the witch character

https://gyazo.com/c55e4e7985a858b30ed1e6cb33a54bd0

and the export split still dont bring the alpha in the folder

**Comment by Perfare** [comment]
I think this is a fbx compatibility issue with your importer. I tested that the exported fbx file works fine in Blender or other programs.
What does "alpha" mean?

**Comment by Franada** [comment]
https://gyazo.com/83269f131723e5f81da4f8011e73e9f5

in other game there is only the fbx in the folder and no texture to be found

**Comment by Franada** [comment]
what could explain my rig problem. its doing the same in 3ds max.

**Comment by Perfare** [comment]
I need some time to research the rig problem. 
There is some information you need to provide. What version and format do you use to export fbx? And what version of 3ds max are you using?
About texture issues, only when the image is connected to the Material is in the usual situation, AssetStudio can set it in fbx and export it. Such as "_MainTex" and "_BumpMap".

**Comment by Franada** [comment]
here my fbx for an example. if its only on my pc that would be weird . 

https://mega.nz/#!GupG3YTA!I3vdYOomZH_i0GAFLeZIf9EQunzr1Z8iGVhUMNudeE8

**Comment by Perfare** [comment]
I am very sorry, you gave me the file I tested a lot of software and works fine. Can't find the problem in your screenshot
